export const housePriceData = [
    { id: 1, name: 'St Albans (AL)', link: '#' },
    { id: 2, name: 'Birmington (B)', link: '#' },
    { id: 3, name: 'Bath (BA)', link: '#' },
    { id: 4, name: 'Balckburn (BB)', link: '#' },
    { id: 5, name: 'Bradford (BD)', link: '#' },
    { id: 6, name: 'Bournemouth (BH)', link: '#' },
    { id: 7, name: 'Bolton (AL)', link: '#' },
    { id: 8, name: 'Brighton(B)', link: '#' },
    { id: 9, name: 'Bromeley (BR)', link: '#' },
    { id: 10, name: 'Bristol (BS)', link: '#' },
    { id: 11, name: 'Carlisle (CA)', link: '#' },
    { id: 12, name: 'Cambridge (CB)', link: '#' },
    { id: 13, name: 'Conventry (CV)', link: '#' },
    { id: 14, name: 'Crewe (CW)', link: '#' },
    { id: 15, name: 'Dartford (DA)', link: '#' },
    { id: 16, name: 'Derby (DE)', link: '#' },
    { id: 17, name: 'Durham (DH)', link: '#' },
    { id: 18, name: 'Darlington (DL)', link: '#' },
    { id: 19, name: 'Doncaster (DN)', link: '#' },
    { id: 20, name: 'Dorchester(DT)', link: '#' },
    { id: 21, name: 'Dudely (DY)', link: '#' },
    { id: 22, name: 'Enfield (EN)', link: '#' },
    { id: 23, name: 'Exeter (EX)', link: '#' },
    { id: 24, name: 'Blackpool (FY)', link: '#' },
    { id: 25, name: 'Gloucester (GL)', link: '#' },
    { id: 26, name: 'Guildford (GU)', link: '#' },
    { id: 27, name: 'Harrow (HA)', link: '#' },
    { id: 28, name: 'Huddersfield (HD)', link: '#' },
    { id: 29, name: 'Harrogate (HG)', link: '#' },
    { id: 30, name: 'Hemel Hemp (HP)', link: '#' },
    { id: 31, name: 'Hereford (HR)', link: '#' },
    { id: 32, name: 'Hull (HU)', link: '#' },
    { id: 33, name: 'Halifax (HX)', link: '#' },
    { id: 34, name: 'illford (IG)', link: '#' },
    { id: 35, name: 'Kings UpT (KT)', link: '#' },
    { id: 36, name: 'Liverpool (L)', link: '#' },
    { id: 37, name: 'Lancaster (LA)', link: '#' },
    { id: 38, name: 'Llandrindod (LD)', link: '#' },
    { id: 39, name: 'Leicester (LE)', link: '#' },
    { id: 40, name: 'LLandudno (LL)', link: '#' },
    { id: 41, name: 'Lincoln (LN)', link: '#' },
    { id: 42, name: 'London', link: '#' },
    { id: 43, name: 'Leeds (LS)', link: '#' },
    { id: 44, name: 'Luton (LU)', link: '#' },
    { id: 45, name: 'Manchester (M)', link: '#' },
    { id: 46, name: 'Rochester (ME)', link: '#' },
    { id: 47, name: 'Milton Keynes (MK)', link: '#' },
    { id: 48, name: 'Nottingham (NG)', link: '#' },
    { id: 49, name: 'Northhampton (NN)', link: '#' },
    { id: 50, name: 'Newport (NP)', link: '#' },
    { id: 51, name: 'Norwich (NR)', link: '#' },
    { id: 52, name: 'Oldham (OL)', link: '#' },
    { id: 53, name: 'Oxford (OX)', link: '#' },
    { id: 54, name: 'Peterborough (PE)', link: '#' },
    { id: 55, name: 'Plymouth (PL)', link: '#' },
    { id: 56, name: 'Portsmouth (PO)', link: '#' },
    { id: 57, name: 'Preston (PR)', link: '#' },
    { id: 58, name: 'Reading (RG)', link: '#' },
    { id: 59, name: 'Redhill (RH)', link: '#' },
    { id: 60, name: 'Sheffield (S)', link: '#' },
    { id: 61, name: 'Swansea (SA)', link: '#' },
    { id: 62, name: 'Stevenage (SG)', link: '#' },
    { id: 63, name: 'Stockport (SK)', link: '#' },
    { id: 64, name: 'Slough (SL)', link: '#' },
    { id: 65, name: 'Sutton (SM)', link: '#' },
    { id: 66, name: 'Swindon (SN)', link: '#' },
    { id: 67, name: 'Southampton (SO)', link: '#' },
    { id: 68, name: 'Salisbury (SO)', link: '#' },
    { id: 69, name: 'Sunderland (SR)', link: '#' },
    { id: 70, name: 'Stock (ST)', link: '#' },
    { id: 71, name: 'Shrewsbury (SY)', link: '#' },
    { id: 72, name: 'Taunton (TA)', link: '#' },
    { id: 73, name: 'Galashiels (TD)', link: '#' },
    { id: 74, name: 'Telford (TF)', link: '#' },
    { id: 75, name: 'Tonbridge (TN)', link: '#' },
    { id: 76, name: 'Torquay (TQ)', link: '#' },
    { id: 77, name: 'Truro (TR)', link: '#' },
    { id: 78, name: 'Cleveland (TS)', link: '#' },
    { id: 79, name: 'Twickenham (TW)', link: '#' },
    { id: 80, name: 'Southhall (UB)', link: '#' },
    { id: 81, name: 'Warrington (WA)', link: '#' },
    { id: 82, name: 'Watford (WD)', link: '#' },
    { id: 83, name: 'Wakefield (WF)', link: '#' },
    { id: 84, name: 'Wigan (WN)', link: '#' },
    { id: 85, name: 'Worcester (WR)', link: '#' },
    { id: 86, name: 'Walsall (WS)', link: '#' },
    { id: 87, name: 'Wolverham (WV)', link: '#' },
    { id: 88, name: 'York (YO)', link: '#' },
]